In [1]:
# pytorch
import torch

## Finding the min, max, mean, sum, etc (aggregation)

حالا که چند روش برای دستکاری دیتا ها یاد گرفتیم ، میتونیم محاسبات تجمیعی روی دیتا انجام بدیم


In [2]:
# Create a tensor
x = torch.arange(0, 100, 10.)
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [3]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Mean: {x.mean()}")
print(f"Sum: {x.sum()}")

Minimum: 0.0
Maximum: 90.0
Mean: 45.0
Sum: 450.0


<div dir="rtl">
    
> **نکته:** این دستور نیاز به `torch.float32` داره، انواع دیگه دیتا باعث خطا میشه 
    
</div>

In [4]:
# Create a tensor
y = torch.arange(0, 100, 10, dtype=torch.int32)
y

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int32)

In [5]:
print(f"Minimum: {y.min()}")
print(f"Maximum: {y.max()}")
# print(f"Mean: {y.mean()}") # this will error
print(f"Mean: {y.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {y.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


## Positional min/max

با دستورات زیر میتونیم موقعیت کمترین و بیشترین مقدار رو در یک تنسور پیدا کنیم:

[`torch.argmax()`](https://pytorch.org/docs/stable/generated/torch.argmax.html) and [`torch.argmin()`](https://pytorch.org/docs/stable/generated/torch.argmin.html)

In [6]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


## Change tensor datatype

همونطور که قبلا اشاره کردیم، یکی از خطاهای متداول در پروسه یادگیری عمیق ، داشتن دیتا تایپ های متفاوت هست.

که به راحتی قابل حل کردن هست، میتونیم با دستورات زیر نوع دیتا های درون تنسور رو عوض کنیم.

In [7]:
# Create a tensor and check its datatype
tensor = torch.arange(10, 100, 10)
tensor.dtype

torch.int64

In [8]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [9]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [10]:
# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

> **Note:** Different datatypes can be confusing to begin with. But think of it like this, the lower the number (e.g. 32, 16, 8), the less precise a computer stores the value. And with a lower amount of storage, this generally results in faster computation and a smaller overall model. Mobile-based neural networks often operate with 8-bit integers, smaller and faster to run but less accurate than their float32 counterparts. For more on this, I'd read up about [precision in computing](https://en.wikipedia.org/wiki/Precision_(computer_science)).

> **Exercise:** So far we've covered a fair few tensor methods but there's a bunch more in the [`torch.Tensor` documentation](https://pytorch.org/docs/stable/tensors.html), I'd recommend spending 10-minutes scrolling through and looking into any that catch your eye. Click on them and then write them out in code yourself to see what happens.

## Reshaping, stacking, squeezing and unsqueezing

خیلی از اوقات ما نیاز داریم ماتریسها / تنسورها رو تغییر شکل/ابعاد بدیم بدون اینکه دیتا اصلی تغییر کنه.

اینها روشهای اصلی این تغییرها هستند:


| روش | توضیحات |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | Reshapes `input` to `shape` (if compatible), can also use `torch.Tensor.reshape()`. |
| [`torch.Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Returns a view of the original tensor in a different `shape` but shares the same data as the original tensor. |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Concatenates a sequence of `tensors` along a new dimension (`dim`), all `tensors` must be same size. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Squeezes `input` to remove all the dimenions with value `1`. |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Returns `input` with a dimension value of `1` added at `dim`. | 
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Returns a *view* of the original `input` with its dimensions permuted (rearranged) to `dims`. | 

چرا مهمه?

چون در یادگیری عمیق همیشه ما نیاز به اعمال تغییرات و ضرب ماتریس ها (تنسور) داریم. و چون این محاسبات قوانین مشخصی برای شکل و ابعاد ماتریس ها دارند ، نیاز داریم این ابعاد رو با توجه به کاری که میخواهیم بکنیم ، تغییر بدیم. این روش ها به ما کمک میکنند بتونیم این تغییرات رو انجام بدیم.

In [11]:
# Create a tensor
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

### reshape()
حالا یک بعد به ماتریس/تنسور اضافه میکنیم 

`torch.reshape()`. 

In [12]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

### view()
میتونیم نما یا شکل نمایش تنسور رو عوض کنیم

`torch.view()`.

In [13]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

<div dir="rtl">
    
عوض کردن نحوه نمایش تنسور با دستور torch.view(tensor) فقط نحوه نمایش رو عوض میکنه و هنوز به دیتا اصلی اشاره میکنه

بنابر این اگر مقدار نما رو عوض کنید ، دیتا اصلی هم تغییر میکنه.
    
</div>

In [14]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

### stack()
از دستور زیر برای روی هم گذاشتن تنسورها میتونیم استفاده کنیم:

`torch.stack()`.

In [25]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

### squeeze()

حذف کردن یک بعد از تنسور

In [26]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


### unsqueeze()

اضافه کردن یک بعد به تنسور (برعکس دستور قبلی)

In [27]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


### permute()

تغییر دادن جای ابعاد مختلف یک تنسور

>نکته: چون خروجی این دستور یک ویو هست ، اگر دیتا تنسور خروجی تغییر کند ، دیتا تنسور اصلی هم تغییر میکند

In [28]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (selecting data from tensors)

انتخاب یک عضو (مثلا یک دیتا یا یک سطر یا یک ستون)

In [29]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [30]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


**عملگر :**

میتونید از : برای گرفتن همه مقادیر در اون بعد استفاده کنید


In [34]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [32]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [35]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]


tensor([5])

In [36]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])