## PyTorch tensors & NumPy

- **torch.from_numpy(ndarray)**    - NumPy array     -->  PyTorch tensor.
- **torch.Tensor.numpy()**         - PyTorch tensor  -->  NumPy array.

In [1]:
# NumPy array -> PyTorch tensor 
import torch
import numpy as np
array = np.arange(1.0, 10.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [2]:
array.dtype , tensor.dtype

(dtype('float64'), torch.float64)

<div dir="rtl">

نوع داده پیش فرض در NumPy از نوع float43 هست

وقتی از NumPy به PyTorch تبدیل میکنیم ، نوع داده از متغیر مبدا کپی میشه
    
    
    
</div>

In [3]:
tensor = torch.from_numpy(array).type(torch.float32)

In [4]:
tensor.dtype

torch.float32

In [5]:
array = array + 2
array , tensor

(array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [7]:
# NumPy array -> PyTorch tensor
tensor = torch.zeros(8)
numpy_tensor = tensor.numpy()
tensor , numpy_tensor

(tensor([0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32))

In [8]:
tensor.dtype , numpy_tensor.dtype

(torch.float32, dtype('float32'))

In [9]:
tensor = tensor + 1
tensor , numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1., 1.]),
 array([0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32))

### Reproducibility 

تکرار الگوهای تصادفی

در طول این دوره به اهمیت تولید اعداد تصادفی در ساخت و استفاده از شبکه های عصبی و یادگیری ماشین بیشتر پی میبریم

بیشتر مدلهای شبکه های عصبی و هوش مصنوعی به طور کلی از روند زیر پیروی میکنند:

1. با اعداد تصادفی شروع کن
2. محاسبات مورد نظر رو انجام بده
3. نتایج رو بهتر کن
4. همین روند رو تکرار کن


با اینکه تولید اعداد تصادفی مهم و حیاتی هستند برای این پروسه ، گاهی ما نیاز داریم (برای آزمایش یا تکرار نتایج و بررسی) همون اعداد رو تولید کنیم

In [21]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.3906, 0.6538, 0.6440, 0.8795],
        [0.6813, 0.9011, 0.4105, 0.3022],
        [0.3226, 0.4308, 0.6492, 0.8568]])

Tensor B:
tensor([[0.4829, 0.5384, 0.8557, 0.2473],
        [0.2483, 0.4148, 0.4512, 0.1732],
        [0.0494, 0.2218, 0.4972, 0.8161]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

### Random Seed

Wikipedia: https://en.wikipedia.org/wiki/Random_seed

PyTorch Docs: https://pytorch.org/docs/stable/notes/randomness.html


In [24]:
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# Tensors on GPUs



<div dir="rtl">

    
CPU یا Central Processing Unit (واحد پردازش مرکزی)، یک قطعه سخت‌افزاری است که مسئول اجرای برنامه‌ها و دستورات سیستمی در یک سیستم کامپیوتری است. CPU در عملیات‌های متناوب، محاسباتی سنگین و کاربردهای گسترده دیگر به کار می‌رود. به طور کلی، CPU مجهز به تعداد کمی هسته پردازشی (معمولاً ۲ تا ۱۶ هسته) است، هر کدام با سرعت بالایی اجرا می‌شوند، با توجه به فرکانس ساعت (clock speed) آن‌ها.

اما GPU یا Graphics Processing Unit (واحد پردازش گرافیکی) برای کاربردهای گرافیکی به کار می‌رود، مثل بازی‌های ویدیویی، ویرایش ویدیو و عکس و محاسبات علمی. GPU با تعداد زیادی هسته پردازشی (معمولاً بیشتر از ۱۰۰۰ هسته) و فرکانس ساعت پایین‌تر از CPU، برای انجام محاسبات گرافیکی و محاسبات ماتریسی بسیار سریع است.

به طور کلی، CPU برای محاسبات عمومی و سنگین، مانند محاسبات شبکه‌های عصبی و پردازش صوتی و متنی مناسب است. از سوی دیگر، GPU برای محاسبات گرافیکی و علمی، مانند محاسبات شبیه‌سازی فیزیکی، یادگیری ژرف و شبکه‌های عصبی عظیم الجثه، مناسب است.

    
</div>



### Getting a GPU


| **روش** | **راه اندازی** | **مزایا** | **معایب** | **راهنما** |
| ----- | ----- | ----- | ----- | ----- |
| Google Colab | Easy | Free to use, almost zero setup required, can share work with others as easy as a link | Doesn't save your data outputs, limited compute, subject to timeouts | [Follow the Google Colab Guide](https://colab.research.google.com/notebooks/gpu.ipynb) |
| Use your own | Medium | Run everything locally on your own machine | GPUs aren't free, require upfront cost | Follow the [PyTorch installation guidelines](https://pytorch.org/get-started/locally/) |
| Cloud computing (AWS, GCP, Azure) | Medium-Hard | Small upfront cost, access to almost infinite compute | Can get expensive if running continually, takes some time ot setup right | Follow the [PyTorch installation guidelines](https://pytorch.org/get-started/cloud-partners/) |




To check if you've got access to a Nvidia GPU, you can run `!nvidia-smi` where the `!` (also called bang) means "run this on the command line".

In [28]:
!nvidia-smi

Sun Mar 19 23:24:28 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.04              Driver Version: 531.29       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3080 Ti      On | 00000000:01:00.0  On |                  N/A |
|  0%   34C    P8               32W / 370W|   1368MiB / 12288MiB |     11%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

<div dir="rtl">

اگر `GPU` ندارید یا درایور نصب نباشه پیغامی شبیه به این ممکنه بگیرید:
 
</div>

`
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
`


### PyTorch on GPU

#### TORCH.CUDA
##### This package adds support for CUDA tensor types, that implement the same function as CPU tensors, but they utilize GPUs for computation.

It is lazily initialized, so you can always import it, and use is_available() to determine if your system supports `CUDA`.

`CUDA` semantics has more details about working with `CUDA`.

https://pytorch.org/docs/stable/cuda.html

#### Check GPU / CUDA

In [35]:
# Check for GPU
import torch
torch.cuda.is_available()

True

#### Set device to CUDA / GPU

In [33]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

#### Multi GPU

In [37]:
# Multi GPU
# Count number of devices
torch.cuda.device_count()

1

#### Putting tensors (and models) on the GPU

`.to(device)` return a `COPY` of tensor on the other deive, thus tensor will be on both `CPU` and `GPU`.


In [38]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

#### Moving tensors back to the CPU

In [41]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [42]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [43]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

***تمرین ها: [لینک به فایل تمرین ها](Ex%2001%20-%20تمرینات.ipynb)***


**Intro:** https://pytorch.org/tutorials/beginner/basics/intro.html

**Quick Start:** https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html

**Tensors:** https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html