تمرینات:

### 1. منابع


**Intro:** https://pytorch.org/tutorials/beginner/basics/intro.html

**Quick Start:** https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html

**Tensors:** https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html


### 2. یک تنسور تصادفی 7 در 7 ایجاد کنید



In [7]:
# Import torch

# Create random tensor


### 3. تنسور قبل را در یک تنسور تصادفی 1 در 7 ضرب کنید


In [8]:
# Create another random tensor

# Perform matrix multiplication 

### 4.  هسته تولید عدد تصادفی را روی 0 ست کنید و مراحل 2 و 3 را تکرار کنید

خروجی باید برابر با مقدار زیر باشد:

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))

In [9]:
# Set manual seed

# Create two random tensors

# Matrix multiply tensors

### 5.   (اگر جی چی یو دارید)  مرحله 4 رو برای جی پی یو تکرار کنید

- هسته تولید عدد تصادفی رو در جی پی یو روی 1234 ست کنید

In [10]:
# Set random seed on the GPU

### 6. دو تنسور تصادفی 2 در 3 ایجاد کنید، هر دو رو به جی چی یو منتقل کنید

- هسته تصادفی رو روی 1234 ست کنید
- نکته: هسته تصادفی برای سی پی یو ست میشه
- خروجی باید معادل زیر باشه

Device: cuda

(tensor([[0.0290, 0.4019, 0.2598], 
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
         
 tensor([[0.0518, 0.4681, 0.6738], 
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [11]:
# Set random seed

# Check for access to GPU

# Create two random tensors on GPU

### 7. دو تنسور مرحله قبل رو در هم ضرب کنید

- ممکنه نیاز داشته باشید ابعاد تنسور رو تغییر بدید
- خروجی باید معادل زیر باشه

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))


In [12]:
# Perform matmul on tensor_A and tensor_B

### 8. مقدار بیشترین و کمترین رو در تنسور مرحله 7 پیدا کنید

In [ ]:
# Find max

# Find min

### 9. موقعیت مقدار بیشترین و کمترین رو در تنسور مرحله 7 پیدا کنید

In [14]:
# Find index max

# Find index min

### 10.
- (1, 1, 1, 10)  یک تنسور 1 در 1 در 1 در 10 ایجاد کنید
- همه ابعاد 1 رو از تنسور حذف کنید (فقط بعد 10 باقی بمونه)
- هسته تصادفی رو روی 7 ست کنید
- تنسور اصلی و خروجی مرحله قبل رو به همراه شکل تنسور ها چاپ کنید
- خروجی باید معادل زیر باشد

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])

In [15]:
# Set seed


# Create random tensor


# Remove single dimensions


# Print out tensors and their shapes